import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';

class PDFGeneratorService {
  /// 生成合规护照 PDF
  Future<File> generateCompliancePassport({
    required String transactionId,
    required Map<String, dynamic> producer,
    required Map<String, dynamic> processor,
    required Map<String, dynamic> wasteDetails,
    String? collectionAddress,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            _buildHeader(),
            pw.SizedBox(height: 30),

            // Certificate Title
            pw.Center(
              child: pw.Text(
                'WASTE TRANSPORT COMPLIANCE CERTIFICATE',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),

            // Certificate Details
            _buildSection('Certificate Information', [
              ['Certificate No:', 'BBX-$transactionId'],
              ['Issue Date:', DateFormat('dd/MM/yyyy').format(DateTime.now())],
              [
                'Valid Until:',
                DateFormat('dd/MM/yyyy')
                    .format(DateTime.now().add(const Duration(days: 30)))
              ],
              ['Transaction ID:', transactionId],
            ]),

            pw.SizedBox(height: 20),

            // Producer Information
            _buildSection('Producer Information', [
              ['Company:', producer['companyName'] ?? 'N/A'],
              ['Contact Person:', producer['displayName'] ?? 'N/A'],
              ['Email:', producer['email'] ?? 'N/A'],
              ['Contact:', producer['contact'] ?? 'N/A'],
              ['City:', producer['city'] ?? 'N/A'],
            ]),

            pw.SizedBox(height: 20),

            // Processor Information
            _buildSection('Processor Information', [
              ['Company:', processor['companyName'] ?? processor['name'] ?? 'N/A'],
              ['Contact Person:', processor['displayName'] ?? 'N/A'],
              ['Email:', processor['email'] ?? 'N/A'],
              ['Contact:', processor['contact'] ?? 'N/A'],
              ['City:', processor['city'] ?? 'N/A'],
            ]),

            pw.SizedBox(height: 20),

            // Waste Details
            _buildSection('Waste Details', [
              ['Type:', wasteDetails['wasteType'] ?? 'N/A'],
              ['Quantity:', '${wasteDetails['quantity']} ${wasteDetails['unit']}'],
              ['Description:', wasteDetails['title'] ?? wasteDetails['description'] ?? 'N/A'],
              if (collectionAddress != null) ['Collection Address:', collectionAddress],
            ]),

            pw.SizedBox(height: 30),

            // PCDS 2030 Compliance Section
            _buildComplianceSection(),

            pw.SizedBox(height: 30),

            // QR Code placeholder (text for now, can be replaced with actual QR)
            pw.Center(
              child: pw.Container(
                width: 100,
                height: 100,
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey400),
                ),
                child: pw.Center(
                  child: pw.Text(
                    'QR Code\n$transactionId',
                    textAlign: pw.TextAlign.center,
                    style: const pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600,
                    ),
                  ),
                ),
              ),
            ),

            pw.SizedBox(height: 30),

            // Footer
            pw.Align(
              alignment: pw.Alignment.center,
              child: pw.Text(
                'This certificate is digitally generated by BBX Platform\n'
                'For verification, visit: https://bbx.example.com/verify/$transactionId',
                style: pw.TextStyle(
                  fontSize: 9,
                  fontStyle: pw.FontStyle.italic,
                  color: PdfColors.grey600,
                ),
                textAlign: pw.TextAlign.center,
              ),
            ),
          ];
        },
      ),
    );

    // Save to file
    final output = await getApplicationDocumentsDirectory();
    final file = File('${output.path}/compliance_passport_$transactionId.pdf');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  /// 构建 PDF 头部
  pw.Widget _buildHeader() {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColors.green700,
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Text(
            'BBX COMPLIANCE PASSPORT',
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            'Borneo Biomass Exchange',
            style: const pw.TextStyle(
              fontSize: 14,
              color: PdfColors.white,
            ),
          ),
        ],
      ),
    );
  }

  /// 构建信息段落
  pw.Widget _buildSection(String title, List<List<String>> items) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.green700,
          ),
        ),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          children: items.map((item) {
            return pw.TableRow(
              children: [
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Text(
                    item[0],
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 11,
                    ),
                  ),
                ),
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Text(
                    item[1],
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ),
              ],
            );
          }).toList(),
        ),
      ],
    );
  }

  /// 构建合规认证部分
  pw.Widget _buildComplianceSection() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.green),
        borderRadius: pw.BorderRadius.circular(5),
        color: PdfColors.green50,
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'PCDS 2030 COMPLIANCE CERTIFICATION',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.green700,
            ),
          ),
          pw.SizedBox(height: 10),
          _buildCheckItem('Waste source verified and documented'),
          _buildCheckItem('Transportation route optimized'),
          _buildCheckItem('Environmental impact assessment completed'),
          _buildCheckItem('Sustainable disposal/processing method confirmed'),
          _buildCheckItem('Carbon footprint calculation included'),
          _buildCheckItem('PCDS 2030 compliance standards met'),
        ],
      ),
    );
  }

  /// 构建检查项
  pw.Widget _buildCheckItem(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        children: [
          pw.Container(
            width: 12,
            height: 12,
            decoration: pw.BoxDecoration(
              color: PdfColors.green700,
              shape: pw.BoxShape.circle,
            ),
            child: pw.Center(
              child: pw.Text(
                '✓',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.white,
                ),
              ),
            ),
          ),
          pw.SizedBox(width: 8),
          pw.Expanded(
            child: pw.Text(
              text,
              style: const pw.TextStyle(fontSize: 11),
            ),
          ),
        ],
      ),
    );
  }
}
